camunda/infraex-common-config

- default.json5
related to https://github.com/camunda/team-infrastructure-experience/issues/196
Combines the customManagers to a single one dealing with the same topic of updating dependency versions.
Meaning one is quite flexible in all mentioned files on how a dependency is defined.
> chore(renovate): update customManger definition

- default.json5
related to https://github.com/camunda/team-infrastructure-experience/issues/196
we decided to move KeyCloak specifics to its repository.
> chore(renovate): move keycloak specifics to repository

- .github/workflows/scripts/aws_cleanup.sh
since we removed s3 from cloud nuke we may have had some leftover nightlies.
This aims to fix it by removing any bucket that contains nightly.
> chore(cleanup): remove nightly s3 buckets

- .github/workflows/aws_nightly_cleanup.yml
multi-region saas requires both regions, eval takes 2-3 weeks.
I'll see that I do regular cleanups of unrelated / unused resources.
> chore(gha): disable cleanup triggers due to poc

- .github/workflows/aws_nightly_cleanup.yml
Reverts camunda/infraex-common-config#41
when the POC is over of https://github.com/camunda/team-infrastructure-experience/issues/331 should be reverted.
> Revert "chore(gha): disable cleanup triggers due to poc"

- .github/workflows/aws_nightly_cleanup.yml
- .github/workflows/scripts/aws_global_cleanup.sh
- .github/workflows/scripts/aws_regional_cleanup.sh
Splits up the regional and global cleanup.
The global cleanup script will be run only in one matrix build.
We could outsource it to another runner, but what for repeating ourselves on the same procedure again?
> fix: global resources only run in one matrix cleanup

- .github/workflows/scripts/aws_regional_cleanup.sh
related to https://camunda.slack.com/archives/C076N4G1162/p1729832723460519
`DRY_RUN` wasn't set in one of the scripts and we have pipefail enabled for unset variables.
related run: https://github.com/camunda/infraex-common-config/actions/runs/11513079970/job/32049139658
waiting shortly for it to run through and would go ahead with merging.
> fix: set default value for DRY_RUN

- .github/workflows/aws_nightly_cleanup.yml
related to https://camunda.slack.com/archives/C076N4G1162/p1730008108484239
Doubles the timeout time for cloud-nuke.
> fix: double timeout minutes for cleanup

- .github/workflows/scripts/aws_global_cleanup.sh
We need to exclude the cloudformation stacksets role from being deleted, since its needed for cloudformation in the AWS management account to be able to deploy the Wiz connector resources into the account.
Since its a role that gets created automatically when creating the cloudformation stack and not supposed to be deleted, it would need to be created manually this time
Cloudtrail logs related to the role deletion 
Role creation;
Type: Custom trust policy
Custom trust policy:
`{
"Version": "2012-10-17",
"Id": "stacksets-exec-17b1ba2d4b46b1c7ed312b029f146659-assume-role-policy",
"Statement": [
{
"Sid": "1",
"Effect": "Allow",
"Principal": {
"AWS": "arn:aws:iam::912534604991:role/aws-service-role/stacksets.cloudformation.amazonaws.com/AWSServiceRoleForCloudFormationStackSetsOrgAdmin"
}, …
> fix: prevent deleting cloudformation role for wiz connector creation

- .github/workflows/lint-global.yml
- .github/workflows/lint.yml
- adds a cache for asdf installation to speed up e.g. linting.
Example:
- Previous run: https://github.com/camunda/infraex-common-config/actions/runs/12709016291/job/35427159657?pr=163 (creating the cache)
- New run: https://github.com/camunda/infraex-common-config/actions/runs/12709054296/job/35427281995 (restoring the cache)
> feat: add asdf tool cache

- .github/actions/asdf-install-tooling/action.yml
asdf keeps getting committed and pushed to some of our repositories.
Workflow that runs the change - https://github.com/camunda/infraex-common-config/actions/runs/13971440577/job/39114043739?pr=212#step:4:28
Will automerge after successful run, don't think needs extra review.
> fix: move asdf install to tmp

- .github/workflows/aws_nightly_cleanup.yml
- .github/workflows/scripts/aws_global_cleanup.sh
- .github/workflows/scripts/aws_regional_cleanup.sh
With `read` it was limited to a 100 items, not sure where the problem exactly stems from. Didn't look into it in detail.
With the alternative, it can process more than 100 items into an array.
I've also added `dry run` as default for PRs, so it runs through everything in dry run and we can see what happens.
Dry run being default also allows us to time it better when it should actually be run and not on every single PR impacting others.
> fix: global cleanup

- default.json5
Related to https://github.com/camunda/camunda-deployment-references/pull/225
it was previously only covering `patches`, so e.g. `digest` could schedule whenever.
> fix: add additional updateTypes to schedule

- .github/workflows/aws_nightly_cleanup.yml
Related to https://camunda.slack.com/archives/C076N4G1162/p1743830334303069
We apparently had too many IAM resources that to be deleted within 15 minutes. Bumping the timeout.
> chore: bump timeout of global cleanup step

- default.json5
related to https://github.com/camunda/team-infrastructure-experience/issues/614
adjusts the regex for the helm chart to be able to parse both the old and new tag
```
camunda-platform-8.6-11.3.0
camunda-platform-11.3.0
```
Example based on my private repo:
In the case of `stable/x.y` we don't have to add any versioning or so since we only do `minor`, `patch` anyway for the package, so the major one wouldn't be passed along.
Besides that. I haven't fully understood how Renovate deals with the `github-tags` yet, as it found the major but never anything but the latest tag. So I have been unable so far to get a minor or patch release on a `stable` branch of this package. Once I got it to work but afterwards not again, as said not sure how Renovate deals with the tags.
The only workaround I had …
> chore: extend regex for helm chart tags

- default.json5
related to https://github.com/camunda/team-infrastructure-experience/issues/680
For now ignoring Trivy to deal with the upgrades separately.
From mend:
> chore: tmp ignore trivy to adress upgrade separately

- .github/actions/asdf-install-tooling/action.yml
shellcheck has had problems with the python installation missing zlma, similar to azure cli (which we postponed atm).
I'm using the same fix locally to properly compile python with the library, same problem with shellcheck.
> Fix python issue

- .pre-commit-config.yaml
- default.json5
Reverts camunda/infraex-common-config#240
Public renovate is still running on Renovate `v39`, not sure until when .... `v40` was released last week. 
Until then we can't update anything here.
> Revert "chore(deps): update pre-commit hook renovatebot/pre-commit-hooks to v40"

- .pre-commit-config.yaml
- default.json5
Reverts camunda/infraex-common-config#242
Renovate has finally updated their public instance to the latest version.
Checked on a private repo, was working properly now.
> chore(deps): update pre-commit hook renovatebot/pre-commit-hooks to v40

- .github/actions/gha-failure-log-analyzer/README.md
- .github/actions/gha-failure-log-analyzer/action.yml
- .github/actions/report-failure-on-slack/action.yml
- .github/workflows/gha-failure-log-analyzer.yml
This idea will add a workflow and action (in case someone wants to just use the action itself) and based on our slack failure output action add to the thread automatically a first assessment for the medic.
It's just an idea.
I'll likely still have to iterate a bit on the prompt as so far the output is a bit meh for slack.
The idea was to keep it lightweight so we can worst case just throw it away / out again without being super intervined with our system.
It could later be extended to add more context from slack itself by older alerts but that's for another day.
Linting will fail as actionlint was last updated 7 months ago by the maintainer and the models permissions stuff was added a month ago. There's also currently no way that I know of to ignore the error.
> hackdays: add gha failure log anaylzer with chatgpt

- .github/workflows/lint-global.yml
- .pre-commit-config.yaml
I'm temporarily switching to the forked actionlint that has the models change included, so we won't have issues here.
I'm subscribed to the upstream issue and PR in case it should move forward and also have reached out to the maintainer.
> chore: tmp switch to forked actionlint
